describe('email error checking', () => {
    it('email without @ symbol', () => {
        cy.visit("business-signup")
        cy.get('[data-testid="registration-email"]').type('hello{Enter}')
        cy.get('[data-testid="registration-password"]').type('Hell0Wor!d')
        cy.get('.sc-RYuTI').click()
        cy.get('[data-testid="email-sign-up"]').click()
        // Note: could check here that the error output is the right error but unsure how to
        cy.get('[data-testid="registration-email-subtext-container"]')
    })
    it('checking the same email will fail second time', () => {
        cy.visit("business-signup")
        cy.get('[data-testid="registration-email"]').type('world@example.com{Enter}')
        cy.get('[data-testid="registration-password"]').type('Hell0Wor!d')
        cy.get('.sc-RYuTI').click()
        cy.get('[data-testid="email-sign-up"]').click()
        cy.visit("business-signup")
        cy.get('[data-testid="registration-email"]').type('world@example.com{Enter}')
        cy.get('[data-testid="registration-password"]').type('Hell0Wor!d')
        cy.get('.sc-RYuTI').click()
        cy.get('[data-testid="email-sign-up"]').click()
        // Note: could check here that the error output is the right error but unsure how to
        cy.get('[data-testid="registration-email-subtext-container"]')})
})
// cy.get('[data-testid="email-sign-up"]').should('not.have.class', 'active')
describe('password error checking', () => {
    // potentially, to be super thorough, could do tests to run all possible combos of invalid passwords
    it('password that is too short', () => {
        cy.visit("business-signup")
        cy.get('[data-testid="registration-email"]').type('h{Enter}')
        cy.get('[data-testid="registration-password"]').type('H0Wor!d')
        cy.get('[data-testid="ds-minimum-length-feedback"] > [data-testid="ds-default-feedback-icon"]')
        cy.get('.sc-RYuTI').click()
        cy.get('[data-testid="ds-minimum-length-feedback"] > .sc-kBRoID > [data-testid="ds-alert-error-icon ds-exclamation-circle-icon"]')
    })
    it('password that does not have a special character', () => {
        cy.visit("business-signup")
        cy.get('[data-testid="registration-email"]').type('h{Enter}')
        cy.get('[data-testid="registration-password"]').type('He0World')
        cy.get('[data-testid="ds-symbol-feedback"] > [data-testid="ds-default-feedback-icon"]')
        cy.get('.sc-RYuTI').click()
        cy.get('[data-testid="ds-symbol-feedback"] > .sc-kBRoID > [data-testid="ds-alert-error-icon ds-exclamation-circle-icon"]')
    })
    it('password that does not have a lowercase', () => {
        cy.visit("business-signup")
        cy.get('[data-testid="registration-email"]').type('h{Enter}')
        cy.get('[data-testid="registration-password"]').type('HE0WOR!D')
        cy.get('[data-testid="ds-letter-casing-feedback"] > [data-testid="ds-default-feedback-icon"]')
        cy.get('.sc-RYuTI').click()
        cy.get('[data-testid="ds-letter-casing-feedback"] > .sc-kBRoID > [data-testid="ds-alert-error-icon ds-exclamation-circle-icon"]')
    })
    it('password that does not have an uppercase', () => {
        cy.visit("business-signup")
        cy.get('[data-testid="registration-email"]').type('h{Enter}')
        cy.get('[data-testid="registration-password"]').type('he0wor!d')
        cy.get('[data-testid="ds-letter-casing-feedback"] > [data-testid="ds-default-feedback-icon"]')
        cy.get('.sc-RYuTI').click()
        cy.get('[data-testid="ds-letter-casing-feedback"] > .sc-kBRoID > [data-testid="ds-alert-error-icon ds-exclamation-circle-icon"]')
    })
    it('password that does not have a number', () => {
        cy.visit("business-signup")
        cy.get('[data-testid="registration-email"]').type('h{Enter}')
        cy.get('[data-testid="registration-password"]').type('HeoWor!d')
        cy.get('[data-testid="ds-numeric-feedback"] > [data-testid="ds-default-feedback-icon"]')
        cy.get('.sc-RYuTI').click()
        cy.get('[data-testid="ds-numeric-feedback"] > .sc-kBRoID > [data-testid="ds-alert-error-icon ds-exclamation-circle-icon"]')
    })
    it('password that does not have a number or symbol', () => {
        cy.visit("business-signup")
        cy.get('[data-testid="registration-email"]').type('h{Enter}')
        cy.get('[data-testid="registration-password"]').type('HeoWorld')
        cy.get('[data-testid="ds-numeric-feedback"] > [data-testid="ds-default-feedback-icon"]')
        cy.get('[data-testid="ds-symbol-feedback"] > [data-testid="ds-default-feedback-icon"]')
        cy.get('.sc-RYuTI').click()
        cy.get('[data-testid="ds-numeric-feedback"] > .sc-kBRoID > [data-testid="ds-alert-error-icon ds-exclamation-circle-icon"]')
        cy.get('[data-testid="ds-symbol-feedback"] > .sc-kBRoID > [data-testid="ds-alert-error-icon ds-exclamation-circle-icon"]')
    })

    it('password that is only lowercase and too short', () => {
        cy.visit("business-signup")
        cy.get('[data-testid="registration-email"]').type('h{Enter}')
        cy.get('[data-testid="registration-password"]').type('heworld')
        cy.get('[data-testid="ds-minimum-length-feedback"] > [data-testid="ds-default-feedback-icon"]')
        cy.get('[data-testid="ds-letter-casing-feedback"] > [data-testid="ds-default-feedback-icon"]')
        cy.get('[data-testid="ds-numeric-feedback"] > [data-testid="ds-default-feedback-icon"]')
        cy.get('[data-testid="ds-symbol-feedback"] > [data-testid="ds-default-feedback-icon"]')
        cy.get('.sc-RYuTI').click()
        cy.get('[data-testid="ds-letter-casing-feedback"] > .sc-kBRoID > [data-testid="ds-alert-error-icon ds-exclamation-circle-icon"]')
        cy.get('[data-testid="ds-minimum-length-feedback"] > .sc-kBRoID > [data-testid="ds-alert-error-icon ds-exclamation-circle-icon"]')
        cy.get('[data-testid="ds-letter-casing-feedback"] > .sc-kBRoID > [data-testid="ds-alert-error-icon ds-exclamation-circle-icon"]')
        cy.get('[data-testid="ds-numeric-feedback"] > .sc-kBRoID > [data-testid="ds-alert-error-icon ds-exclamation-circle-icon"]')
        cy.get('[data-testid="ds-symbol-feedback"] > .sc-kBRoID > [data-testid="ds-alert-error-icon ds-exclamation-circle-icon"]')

    })

})